---
title: "House Elections Package"
author: "Lauren Bergam, Ryan Buckland, Peter Shewmaker"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

## Gross Domestic Product Data (gdp_state and gdp_status)
The functions gdp_state and gdp_status were developed from R code that was being repeated during exploratory analysis of the by-state, per capita Gross Domestic Product (GDP) data from the United States Bureau of Economic Analysis (BEA). As such, these functions are specific to the BEA's GDP dataset.

###gdp_state
The function gdp_state is used to quickly print the a specific state's historic annual per capita GDP data. The only argument in the function is the state.

For example, if I want to know Virginia's historic per capita GDP, I will use "Virginia" as the argument in gdp_state, as follows:

```r
gdp_state("Virginia")
```

###gdp_status
The function gdp_status is used to quickly find out if a specific state's per capita GDP increased over a user-specific time period. There are 3 arguments in the function: state, year1, and year2. 

For example, if I want to know if Virginia's per capita GDP increased between 2012 and 2016, I will use "Virginia", "2012", and "2016" in the function's arguments, as follows:

```r
gdp_status("Virginia","2012","2016")
```

Note: year1 must occur before year2. This is to prevent incorrect conclusions drawn from the function output, as the function is intended for changes over time.